import logging, argparse
from numpy import int32
from numpy.random import normal

from vdif import VDIFFrame

if __name__ == "__main__":

    # Parse the user's command line arguments
    parser = argparse.ArgumentParser(description='Simulate VDIF data from multiple stations')
    parser.add_argument('-v', dest='verbose', action='store_true', help='display debugging logs')
    parser.add_argument('-s', '--total-stations', dest='total_stations', metavar='TOTAL_STATIONS', 
                        type=int, default=1, help='Simulate data generated by TOTAL_STATIONS (default 1)')
    parser.add_argument('-n', '--frames', dest='frames', metavar='FRAMES',
                        type=int, default=1, help='Generate FRAMES of data (default 1)')
    parser.add_argument('-c', '--correlated-level', dest='corr_level', metavar='CORR_LEVEL',
                        type=float, default=1.0, help='Set the level of the correlated component (default 1.0)')
    args = parser.parse_args()

    # Generate our correlated component
    corr_level = args.corr_level
    uncorr_level = 1.0 - corr_level
    corr_component = (2048 * corr_level * normal(size=1024*2)).astype(int32)

    for thread in range(args.total_stations):
        filename = "capt{0}.vdif".format(thread)
        with open(filename, 'wb') as file_:
            for frame_n in range(args.frames):
                vdif_frame = VDIFFrame()
                vdif_frame.bits_per_sample = 32
                vdif_frame.frame_length = 1024
                vdif_frame.data = corr_component + (2048 * uncorr_level * normal(size=1024*2)).astype(int32)
                vdif_frame.data_frame = frame_n
                file_.write(str(vdif_frame))
